# Generated by Django 4.2.10 on 2024-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast', models.TextField(verbose_name='公告内容')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Dsyfunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15, verbose_name='故障项目')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='故障图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('description', models.TextField(verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, '系统消息'), (2, '社团管理员通知'), (3, '房间管理员通知')], verbose_name='消息来源')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('read_status', models.BooleanField(verbose_name='阅读状态')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='图片')),
            ],
        ),
    ]
