# Generated by Django 4.2.10 on 2024-02-20 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='shared_people',
            field=models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
