# Generated by Django 4.2.10 on 2024-02-21 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='shared_people',
            field=models.ManyToManyField(blank=True, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, '系统消息'), (2, '社团管理员通知'), (3, '房间管理员通知')], verbose_name='消息来源'),
        ),
    ]
