# Generated by Django 5.0.1 on 2024-02-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('start_time',)},
        ),
    ]
