# Generated by Django 5.0.1 on 2024-02-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0003_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='over_time',
            field=models.IntegerField(blank=True, choices=[(1, '未超时'), (2, '超时')], null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='sign_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
